AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2010-09-09"
Resources:
  MyApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: "dev" 

  MyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: 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
      Events:
        MyApiEvent:
          Type: Api
          Properties:
            Path: /my-endpoint
            Method: post 
            RestApiId: !Ref MyApi
