name: Deploy Lambda func

on: 
  push: 
    branches: 
      - main

jobs: 
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run script
        run: node index.mjs

      - name: Deploy Lambda
        run: |
          zip -j deploy.zip ./index.mjs
          aws lambda update-function-code --function-name=askAI --zip-file=fileb://deploy.zip
